<?php

/**
 * @file
 * The module file
 *
 * This module makes it possible to remove certain ip's blocked in flood
 */

/**
 * Implements hook_menu().
 */
function flood_unblock_menu() {
  $items['admin/config/system/flood-unblock'] = array(
    'title' => 'Flood unblock',
    'description' => 'Clear flood entries.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flood_unblock_settings'),
    'access arguments' => array('access flood unblock'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function flood_unblock_permission() {
  return array(
    'access flood unblock' => array(
      'title' => t('Access the flood unblock module'),
      ),
    );
}

/**
 * The settings form function
 */
function flood_unblock_settings() {
  $form = array();
  $events = _flood_unblock_get_event_options();
  if (empty($events)) {
    drupal_set_message(t('No flood events to clear.'));
    return $form;
  }
  $form['flood_unblock'] = array(
    '#type' => 'select',
    '#title' => t('Clear which event'),
    '#required' => TRUE,
    '#options' => $events,
  );
  $form['flood_unblock_id'] = array(
    '#type' => 'textfield',
    '#title' => t('What identifer should be cleared'),
    '#required' => FALSE,
    '#description' => t('If this field is empty all chosen events will be cleared.'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Clear flood'),
  );
  return $form;
}

/**
 * The submit function
 */
function flood_unblock_settings_submit($form, &$form_state) {
  flood_unblock_clear_event($form_state['values']['flood_unblock'], $form_state['values']['flood_unblock_id']);
}

/**
 * The function that clear the flood
 */
function flood_unblock_clear_event($type, $ip) {
  $query = db_delete('flood')
    ->condition('event', $type);
  if (isset($ip)) {
    $query->condition('identifier', '%' . $ip, 'LIKE');
  }
  $count = $query->execute();
  drupal_set_message(t('Flood cleared !num entries', array('!num' => $count)));
}

/**
 * Get flood events in FAPI options format.
 *
 * @return array
 */
function _flood_unblock_get_event_options() {
  $events = array();
  $result = db_query("SELECT DISTINCT event FROM {flood}");
  foreach ($result as $record) {
    $events[$record->event] = $record->event;
  }
  return $events;
}